# Site settings
title: Hammit's Dev Blog
email: byron_hammond@yahoo.com.au
description: > # this means to ignore newlines until "baseurl:"
  Here you'll find a small and simple blog for documenting various things I
  find of interest in the I.T. world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hammit.github.io" # the base hostname & protocol for your site
twitter_username: ByronHammit
github_username:  Hammit

remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

# GitHub pages server runs in a different timezone, so when the server builds the site, may skip posts
future: true

# Build settings
include: ['_pages']
markdown: kramdown
